### ISSUE TITLE
建议和nonebot2的py最低版本要求一样

### ISSUE THREAD

**Issue by MoYoez** [SEAFHMC/nonebot-plugin-arcaeabot#1]
如题 一开始安装时发现装不上

发现需要版本3.9+ 这边建议在readme里面写上python的最低版本

最好能和nb2的最低版本一样 ~~懒得升级~~

**Comment by SEAFHMC** [comment]
3.8可以吗，我看了下代码里用了海象表达式。

**Comment by SEAFHMC** [comment]
哦 看了下就两处用了（草，

**Comment by SEAFHMC** [comment]
已在README中写上Python >= 3.8

**Comment by MoYoez** [comment]
w 这样应该就可以用了()
