### ISSUE TITLE
/arc bind "Expecting value"报错问题

### ISSUE THREAD

**Issue by LiebeVerletzt** [SEAFHMC/nonebot-plugin-arcaeabot#13]
……
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

url和token在另一个同样作为查分器的Andreal Bot上通过并成功返回了一张b30，但一直都没能通过这个插件进行加载
其余回复正常，应该只是连不上url的问题
希望能有错误原因指点，或者增加能单独判断url连接是否通过的指令

**Comment by SEAFHMC** [comment]
你的url后面是不是有/botarcapi，有的话删掉就行

**Comment by LiebeVerletzt** [comment]
感谢，之前尝试过但无效（应该是网络问题），但这次网络正常后问题解决了。
正常运行后目前发现的问题是“quonwacca”和“lastendconductor”两首歌在获取base.jpg的时候找的却是3.jpg
[Errno 2] No such file or directory: 'C:\\Users\\Administrator.DESKTOP-B93KCBS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\nonebot_plugin_arcaeabot\\assets\\song\\quonwacca\\3.jpg'
并且我真的把名字改成3后它真的跑起来了（x
是小bug吗？

**Comment by SEAFHMC** [comment]
> 感谢，之前尝试过但无效（应该是网络问题），但这次网络正常后问题解决了。 正常运行后目前发现的问题是“quonwacca”和“lastendconductor”两首歌在获取base.jpg的时候找的却是3.jpg [Errno 2] No such file or directory: 'C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_arcaeabot\assets\song\quonwacca\3.jpg' 并且我真的把名字改成3后它真的跑起来了（x 是小bug吗？

对的，是bug。已经在最新版修复。
