### ISSUE TITLE
插件在群内不能响应/arc help指令

### ISSUE THREAD

**Issue by WindraiteLesd** [SEAFHMC/nonebot-plugin-arcaeabot#14]
/arc help指令在群内无法响应，私聊正常

**Comment by WindraiteLesd** [comment]
github这个code框自己识别错误了

**Comment by WindraiteLesd** [comment]
像/arc help，/arc b30，/arc info这种指令的图片不能发出去，消息可以正常收发，比如bind id指令
gocqhttp端显示消息被风控，按照那边的方法更换协议为安卓后依旧是这样(该方法似乎是解决所有消息都被风控的问题)，其他插件正常发出图片

**Comment by SEAFHMC** [comment]
有没有考虑换个QQ号试试

**Comment by SEAFHMC** [comment]
能不能看一下nb的报错截图

**Comment by WindraiteLesd** [comment]
截图不太好截，我现在是用手机远程操控，不过报错信息基本就是最上面发的那些，如果一定要的话我这周末回家了用电脑再补上截图

**Comment by SEAFHMC** [comment]
你试试直接/arc   会怎样

**Comment by WindraiteLesd** [comment]
输/arc后一样的报错
