### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ZPluto0705** [SEAFHMC/nonebot-plugin-arcaeabot#15]
在准备进行/arc bind时出现

  raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![image](https://user-images.githubusercontent.com/44129124/179351871-2686270d-5b7b-4ea6-8c31-1d84763c8cf4.png)

除了执行/arc help正常输出模块帮助 其他指令都会返回如上图所示的错误

看前面有一个issue也是这个问题 删掉/botarcapi之后依然出现这个问题

**Comment by SEAFHMC** [comment]
config,yml看一下吧，记得中间打码

**Comment by ZPluto0705** [comment]
是插件目录下的config.py嘛，，我没有找到config.yml

**Comment by SEAFHMC** [comment]
bot目录/data/arcaea/config.yml  顺便发一下你插件版本吧

**Comment by ZPluto0705** [comment]
![image](https://user-images.githubusercontent.com/44129124/179355763-04a79c78-05d0-4b3a-a93f-5cfd3a1e0446.png)
yml文件是这个嘛

插件版本的话是3.0.3

**Comment by SEAFHMC** [comment]
aua_url后面是不是有个/
 把那个斜杠也删了

**Comment by ZPluto0705** [comment]
好了 可以啦 谢谢！

![image](https://user-images.githubusercontent.com/44129124/179356845-fa4b33da-1cd9-4d0d-9efc-18bef085ca03.png)

![image](https://user-images.githubusercontent.com/44129124/179356861-64db6f9c-599c-4ea5-9fa4-90027fd1c253.png)

**Comment by ZPluto0705** [comment]
话说可不可以把/arc触发改成/a

**Comment by SEAFHMC** [comment]
> 话说可不可以把/arc触发改成/a

你可以自己在matcher.py的alias里加上"a"
