### ISSUE TITLE
httpx.ConnectTimeout报错

### ISSUE THREAD

**Issue by YOKOKAO** [SEAFHMC/nonebot-plugin-arcaeabot#16]
更新资源以及best,song,random命令会有httpx.ConnectTimeout的报错，查询recent和b30正常。之前各个命令都正常，大概搁置了一个月之后再开莫名有了这个问题，是网络不好吗（？

**Comment by SEAFHMC** [comment]
是cloudflare的锅（
另外建议更新一下插件版本

**Comment by SEAFHMC** [comment]
资源更新实在不行的话试试百度云吧 https://pan.baidu.com/s/1yAirbWQ0JoCfyMgi3R0yIw?pwd=qwv1

**Comment by YOKOKAO** [comment]
解决了，感谢！
