### ISSUE TITLE
当arcaea id开头为0时，无法绑定

### ISSUE THREAD

**Issue by yaowan233** [SEAFHMC/nonebot-plugin-arcaeabot#2]
当arcaea id开头为0时，由于对id取了int，导致判断长度错误
如果绑定成功了，由于数据库里arc id是int类型，在查询时要先在前面加上0才能查询

**Comment by SEAFHMC** [comment]
用以0开头的arcaea_id实验了下，应该能用了。
请先删除旧数据库`(nonebot_plugin_arcaeabot\assets\data.db)`重新绑定，因为旧数据库arcaea_id类型仍为int。

**Comment by SEAFHMC** [comment]
顺便问下0开头的id是什么神仙元老级账号

**Comment by yaowan233** [comment]
056920765 是群友 他是双星人
