### ISSUE TITLE
可以支持/a b30这样的命令吗

### ISSUE THREAD

**Issue by NanakoOfficial** [SEAFHMC/nonebot-plugin-arcaeabot#20]
用/a b30习惯了，/arc命令有没有办法修改
另外图片样式能不能再优化一些（有点不太能一眼看打歌打出的ptt

**Comment by SEAFHMC** [comment]
别称可以在matcher.py的alias里增加"a"
图片样式的话有空再说【

**Comment by NanakoOfficial** [comment]
> 别称可以在matcher.py的alias里增加"a"
> 图片样式的话有空再说【

好的，感谢
