### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by 791814** [SEAFHMC/nonebot-plugin-arcaeabot#30]
![image](https://user-images.githubusercontent.com/117523206/209090215-6325235e-c05b-4916-b29b-92fcda0ce38b.png)
在运行"/a assets_update"指令中，出现报错json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Python版本3.11
已确认插件版本最新

**Comment by SEAFHMC** [comment]
可能是网的问题？ 你试试浏览器能不能打开https://api.ritsuki.top/api/song_list

**Comment by 791814** [comment]
> 可能是网的问题？ 你试试浏览器能不能打开https://api.ritsuki.top/api/song_list

可以打开
![image](https://user-images.githubusercontent.com/117523206/209127203-1038609e-9867-4d4b-acd6-098c8ba437a7.png)

**Comment by 791814** [comment]
同时在使用"/a assets_update --standalone"命令时会出现如下报错：
![image](https://user-images.githubusercontent.com/117523206/209127616-b749c6cb-9e6b-4eda-82a7-65d73b955598.png)
httpx.RemoteProtocolError: peer closed connection without sending complete message body (received 341180416 bytes, expected 984109009)

**Comment by 791814** [comment]
然后又出现如下一系列报错：
![image](https://user-images.githubusercontent.com/117523206/209128682-04baa3fe-53a7-4f84-897c-0be436f666bc.png)

**Comment by SkyDynamic** [comment]
网络问题，挂梯吧
