### ISSUE TITLE
绑定ID报错

### ISSUE THREAD

**Issue by NanakoOfficial** [SEAFHMC/nonebot-plugin-arcaeabot#39]
`    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

账号是/a bind 701292128，插件和依赖都是最新版本，nb2b5，py3.8

**Comment by SEAFHMC** [comment]
昨天似乎api炸了，现在呢？

**Comment by NanakoOfficial** [comment]
> 昨天似乎api炸了，现在呢？

没事了，我一开始以为是我这边依赖出问题了，后来才发现是api炸了，忘了close
