### ISSUE TITLE
选用estertion作为查分Api时函数调用问题

### ISSUE THREAD

**Issue by MoYoez** [SEAFHMC/nonebot-plugin-arcaeabot#4]
![Screenshot_2022-04-07-00-25-58-151_com.sonelli.juicessh.jpg](https://user-images.githubusercontent.com/30306672/162022790-ba2c73f7-3002-43c9-88a7-b55b2cbac019.jpg)

Clone的最新代码() 不知道哪里出问题了

**Comment by MoYoez** [comment]
初步判断可能是和 Nonebot的petpet插件有冲突现象()

或许是个老bug了()

**Comment by SEAFHMC** [comment]
看得出来您应该是选用了estertion的查分api。
但在1.0.0更新以后我删除了adapter.estertion.api中fetch_user_info函数的内容，目的是防止该api被滥用(api作者并不希望有bot爬取他的api)。
如果您坚持要使用的话请自行填补。

**Comment by SEAFHMC** [comment]
亲，你手机没电了（

**Comment by MoYoez** [comment]
az 好叭 过会我试着改改

**Comment by SEAFHMC** [comment]
感谢理解。可以看看[这个](https://gist.github.com/esterTion/c673a5e2547cd54c202f129babaf601d)，应该能帮到你。

**Comment by MoYoez** [comment]
> 感谢理解。可以看看[这个](https://gist.github.com/esterTion/c673a5e2547cd54c202f129babaf601d)，应该能帮到你。

挺奇怪的 刚刚试了试AUA还是不行()

报错一致

**Comment by MoYoez** [comment]
话说回来 其实申请了AUA 会顺带给你

完整的url和token的 建议在配置栏中添加下
/_(:з」∠)_/

刚刚还以为又配置错了.jpg 扒了会源代码才知道这边的问题

**Comment by SEAFHMC** [comment]
我睡醒改改（

**Comment by MoYoez** [comment]
> 我睡醒改改（

抱歉惹 AUA作者回复了下 好像token就是填在User-agent上面的

() 不过在url上面可以删掉 /botarcapi

一般申请的andreal会给完整的url的api地址（）

在AUA请求处可以删掉这一段

**Comment by SEAFHMC** [comment]
apiurl的话我是对标的BotArcApi的文档。
![IMG_20220409_072330](https://user-images.githubusercontent.com/9484642/162546021-32f58ba7-6687-48c1-beb7-e51af06fcdf2.jpg)
不过这样确实比较违反用户习惯，我晚点在文档里写个提醒吧。或者找AUA作者对线（不
