### ISSUE TITLE
py3.8不支持removesuffix

### ISSUE THREAD

**Issue by HSAllenbili** [SEAFHMC/nonebot-plugin-arcaeabot#43]
py3.8出现报错
/home/ubuntu/.local/lib/python3.8/site-packages/nonebot_plugin_arcaeabot/api/request.py
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by SkyDynamic** [comment]
请使用`pip install nonebot_plugin_arcaeabot -U`指令将插件更新至最新版本（

但是我用的镜像源好像只同步到3.1.7版本
如果不行就试试`pip install nonebot_plugin_arcaeabot -U -i https://pypi.org/simple`

**Comment by SEAFHMC** [comment]
如果当前源没有同步最新版而其他源连不上的话可以尝试直接用Github上的源码安装:
1.clone本项目
2.进入bot的虚拟环境(如果使用了venv之类的话)
3.进入clone后的项目目录
4.执行pip install .(这个"."也要, 不是句号)
