### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ArcPav** [SEAFHMC/nonebot-plugin-arcaeabot#45]
大佬能把ai酱也安排上吗(

**Comment by SkyDynamic** [comment]
马上安排（

**Comment by SkyDynamic** [comment]
你是指什么触发命令

ai酱的功能已经写完了，可以看最新的github，不过pip更新没那么快

**Comment by SkyDynamic** [comment]
哦哦这样啊，倒是可以，我甚至可以写个冷却，一定时间内内只能五次那种

就是比较麻烦,毕竟不是UI交互

**Comment by SkyDynamic** [comment]
OK写完了
默认是一个小时内只能查询五次
然后查完一个小时内不能查询但是可以获取最后一次查询的内容

强制重置的话就是重启插件，数据存储是基于内存存储的，就是临时的

**Comment by SkyDynamic** [comment]
自动Close，已经提交上去了，可以覆盖site-packages来体验最新版（

**Comment by SkyDynamic** [comment]
没办法捏，nonebot实现起来就是这样，改起来有点麻烦，还是询问式的好，我看看怎么合并吧，不过别抱太大希望

**Comment by SkyDynamic** [comment]
我自己fork了一份可以触发愚人节的，不提交PR，不并入主版本，仅为我的[魔改版](https://github.com/SkyDynamic/nonebot-plugin-SDarcaeabot)
看看就好了，没必要实装

**Comment by SEAFHMC** [comment]
> 大佬，现在aua是不是废了，听说是616干的

一定是616干的.jpg
