### ISSUE TITLE
请问填写的模板是什么？

### ISSUE THREAD

**Issue by kogekiplay** [SEAFHMC/nonebot-plugin-arcaeabot#5]
我是nonebot的新手，在.env.dev中配置好后还是提示填写不规范
![QQ截图20220413190300.png](https://s2.loli.net/2022/04/13/SQ3fns4tp8gUyPR.png)

**Comment by SEAFHMC** [comment]
可否看看你的.env是怎么写的，写的是不是
ENVIRONMENT=dev

**Comment by kogekiplay** [comment]
是dev，确认过了，难道AUA的token不通用的吗==，我直接从另一个框架复制过来的

**Comment by kogekiplay** [comment]
> 可否看看你的.env是怎么写的，写的是不是 ENVIRONMENT=dev

是dev，确认过了，难道AUA的token不通用的吗==，我直接从另一个框架复制过来的

**Comment by SEAFHMC** [comment]
麻烦提供一下nonebot那边的错误报告

**Comment by kogekiplay** [comment]
大佬明天给你吧，我电脑今天关掉了，暂时挂着原来的框架，错误提示大概是api_in_use填写不规范

**Comment by SEAFHMC** [comment]
从截图看的话还真看不出来哪里错了（顺便问一下你是用什么方式安装和加载的插件

**Comment by kogekiplay** [comment]
用官方商店的命令，直接自动加载的，没改bot.py

**Comment by kogekiplay** [comment]
好的，晚安大佬，明天我再试试

**Comment by SEAFHMC** [comment]
问一下，你的nonebot2版本是不是beta1？
