### ISSUE TITLE
当同一群聊有其它bot时部分命令会引发ai酱触发

### ISSUE THREAD

**Issue by ElainaFanBoy** [SEAFHMC/nonebot-plugin-arcaeabot#52]
比如暮雪酱的猜歌功能/a guess，会导致ai酱触发无限循环![Screenshot_2023-04-14-00-44-52-879_com.tencent.tim.jpg](https://user-images.githubusercontent.com/56375835/231828643-afb00101-a8ee-403b-ba65-1118ebecacf3.jpg)
![Screenshot_2023-04-14-00-45-04-781_com.tencent.tim.jpg](https://user-images.githubusercontent.com/56375835/231828798-ef4f4860-6b09-4a87-9a92-ac99b31fd421.jpg)

**Comment by SkyDynamic** [comment]
奇怪，为啥我不会触发，你修改过部分代码吗

把前缀换成别的应该就不会了

**Comment by SkyDynamic** [comment]
刚看了一下代码，我知道咋回事了
