### ISSUE TITLE
功能列表图片说明错误

### ISSUE THREAD

**Issue by Blokura** [SEAFHMC/nonebot-plugin-arcaeabot#53]
ArcaeaBot Commands 功能列表图片右上角
"[ ] 为必填内容"
"< > 为选填内容"

据测试，应为：
"[ ] 为选填内容"
"< > 为必填内容"

**Comment by SkyDynamic** [comment]
是这样的，画help图的同学画错了（
看我写的文档吧（新版输入help会返回）
那个比较详细

没有别的问题的话就close了

**Comment by Blokura** [comment]
got it

**Comment by Blokura** [comment]
got it
