### ISSUE TITLE
更多功能以及B30作图问题

### ISSUE THREAD

**Issue by RocksonLee** [SEAFHMC/nonebot-plugin-arcaeabot#6]
1. 希望可以增加查询单曲成绩的功能 以及随机曲目推荐
2. b30 作画相对简陋，可参考以下bot或图片生成器进行改进
> https://github.com/Awbugl/Andreal
> https://github.com/Awbugl/AndrealImageGenerator

**Comment by SEAFHMC** [comment]
1、这个可以有.jpg
2、B30图片我感觉还行啊】就信息量的话我觉得挺充实的。是因为主题色调偏暗和半透明字体的原因吗？

**Comment by RocksonLee** [comment]
1. 对于这个b30图片，用一个方框框起来一首歌的信息，目前这个时间是在方框外，观感不是很好，推荐下面的几种目前比较好看的图片

![image](https://user-images.githubusercontent.com/57697347/163673149-1f728958-709b-4730-9b22-fe9dde9d930d.png)

![image](https://user-images.githubusercontent.com/57697347/163673159-d18f4a3d-f534-4318-b644-ba322a4ed92b.png)

![image](https://user-images.githubusercontent.com/57697347/163673171-0d322a89-8aa8-4532-9f3e-834701a96ec1.png)

信息量目前相当充实，可是美观程度可以再调整

2. 发现 AUA 允许查询 b40 （b30往下查询），可以考虑为b30添加至b40，为卑微推歌人一个好方向吧 QWQ

3. 可以对 AUA 支持的功能进行一番适配 （

**Comment by SEAFHMC** [comment]
感谢提供参考图片，开抄.jpg

**Comment by SEAFHMC** [comment]
B30已更新√
